use super::*;
use pretty_assertions::assert_eq;

#[test]
fn should_exclude_test_path_file_from_index_by_default() {
    let files = [(
        "src/repo_test.go".to_string(),
        "package main\n\nfunc TestFoo(t *testing.T) {}\n".to_string(),
    )];
    let resolver = TagsResolver::new(
        files,
        lang_for_path,
        &names(&["TestFoo"]),
        false,
        &HashSet::new(),
        true,
    );

    let expected: Vec<ResolvedSymbol> = Vec::new();
    let actual = resolver.resolve("TestFoo");

    assert_eq!(expected, actual);
}

#[test]
fn should_include_test_path_file_in_index_when_include_tests_is_true() {
    let files = [(
        "src/repo_test.go".to_string(),
        "package main\n\nfunc TestFoo(t *testing.T) {}\n".to_string(),
    )];
    let resolver = TagsResolver::new(
        files,
        lang_for_path,
        &names(&["TestFoo"]),
        true,
        &HashSet::new(),
        true,
    );

    let expected = vec![ResolvedSymbol {
        signature: "func TestFoo(t *testing.T)".to_string(),
        path: "src/repo_test.go".to_string(),
    }];
    let actual = resolver.resolve("TestFoo");

    assert_eq!(expected, actual);
}

#[test]
fn should_exclude_ast_test_definition_from_index_by_default() {
    let files = [(
        "src/lib.rs".to_string(),
        "\
#[cfg(test)]
mod tests {
#[test]
fn should_add_two_numbers() {}
}
"
        .to_string(),
    )];
    let resolver = TagsResolver::new(
        files,
        lang_for_path,
        &names(&["should_add_two_numbers"]),
        false,
        &HashSet::new(),
        true,
    );

    let expected: Vec<ResolvedSymbol> = Vec::new();
    let actual = resolver.resolve("should_add_two_numbers");

    assert_eq!(expected, actual);
}

#[test]
fn should_exclude_file_marked_generated_by_attribute_path_from_index_by_default() {
    let files = [(
        "models/user.go".to_string(),
        "package models\n\nfunc Foo() int {\n\treturn 1\n}\n".to_string(),
    )];
    let generated_paths: HashSet<String> = ["models/user.go".to_string()].into_iter().collect();
    let resolver = TagsResolver::new(
        files,
        lang_for_path,
        &names(&["Foo"]),
        false,
        &generated_paths,
        false,
    );

    let expected: Vec<ResolvedSymbol> = Vec::new();
    let actual = resolver.resolve("Foo");

    assert_eq!(expected, actual);
}

#[test]
fn should_exclude_file_with_generated_content_marker_from_index_by_default() {
    let files = [(
        "models/user.go".to_string(),
        "\
// Code generated by SQLBoiler 4.19.5. DO NOT EDIT.

package models

func Foo() int {
	return 1
}
"
        .to_string(),
    )];
    let resolver = TagsResolver::new(
        files,
        lang_for_path,
        &names(&["Foo"]),
        false,
        &HashSet::new(),
        false,
    );

    let expected: Vec<ResolvedSymbol> = Vec::new();
    let actual = resolver.resolve("Foo");

    assert_eq!(expected, actual);
}

#[test]
fn should_include_generated_file_in_index_when_include_generated_is_true() {
    let files = [(
        "models/user.go".to_string(),
        "\
// Code generated by SQLBoiler 4.19.5. DO NOT EDIT.

package models

func Foo() int {
	return 1
}
"
        .to_string(),
    )];
    let generated_paths: HashSet<String> = ["models/user.go".to_string()].into_iter().collect();
    let resolver = TagsResolver::new(
        files,
        lang_for_path,
        &names(&["Foo"]),
        false,
        &generated_paths,
        true,
    );

    let expected = vec![ResolvedSymbol {
        signature: "func Foo() int".to_string(),
        path: "models/user.go".to_string(),
    }];
    let actual = resolver.resolve("Foo");

    assert_eq!(expected, actual);
}

#[test]
fn should_still_index_ordinary_files_when_a_generated_file_is_excluded() {
    let files = [
        (
            "models/user.go".to_string(),
            "// Code generated by tool. DO NOT EDIT.\n\npackage models\n\nfunc Foo() int {\n\treturn 1\n}\n".to_string(),
        ),
        (
            "src/lib.rs".to_string(),
            "fn helper() -> i32 {\n    1\n}\n".to_string(),
        ),
    ];
    let resolver = TagsResolver::new(
        files,
        lang_for_path,
        &names(&["Foo", "helper"]),
        false,
        &HashSet::new(),
        false,
    );

    let expected_foo: Vec<ResolvedSymbol> = Vec::new();
    let expected_helper = vec![ResolvedSymbol {
        signature: "fn helper() -> i32".to_string(),
        path: "src/lib.rs".to_string(),
    }];
    assert_eq!(expected_foo, resolver.resolve("Foo"));
    assert_eq!(expected_helper, resolver.resolve("helper"));
}

#[test]
fn should_still_index_production_symbols_in_a_file_that_also_has_ast_test_definitions() {
    // A file mixing production code and `#[cfg(test)] mod tests` must
    // still index the production symbol, even with the default
    // test-exclusion on — only the AST-detected test definitions are
    // dropped, not the whole file (unlike a whole-file `is_test_path`
    // match, e.g. `_test.go`).
    let files = [(
        "src/lib.rs".to_string(),
        "\
fn add(a: i32, b: i32) -> i32 {
a + b
}

#[cfg(test)]
mod tests {
#[test]
fn should_add_two_numbers() {}
}
"
        .to_string(),
    )];
    let resolver = TagsResolver::new(
        files,
        lang_for_path,
        &names(&["add"]),
        false,
        &HashSet::new(),
        true,
    );

    let expected = vec![ResolvedSymbol {
        signature: "fn add(a: i32, b: i32) -> i32".to_string(),
        path: "src/lib.rs".to_string(),
    }];
    let actual = resolver.resolve("add");

    assert_eq!(expected, actual);
}

#[test]
fn should_skip_file_with_unsupported_language_when_building_index() {
    let files = [(
        "src/notes.txt".to_string(),
        "helper is defined here".to_string(),
    )];
    let resolver = TagsResolver::new(
        files,
        lang_for_path,
        &names(&["helper"]),
        false,
        &HashSet::new(),
        true,
    );

    let expected: Vec<ResolvedSymbol> = Vec::new();
    let actual = resolver.resolve("helper");

    assert_eq!(expected, actual);
}

#[test]
fn should_index_definitions_across_multiple_languages() {
    let files = [
        (
            "src/lib.rs".to_string(),
            "fn helper() -> i32 {\n    1\n}\n".to_string(),
        ),
        (
            "repo.go".to_string(),
            "package main\n\nfunc greet() string {\n\treturn \"hi\"\n}\n".to_string(),
        ),
    ];
    let resolver = TagsResolver::new(
        files,
        lang_for_path,
        &names(&["helper", "greet"]),
        false,
        &HashSet::new(),
        true,
    );

    let expected = vec![ResolvedSymbol {
        signature: "func greet() string".to_string(),
        path: "repo.go".to_string(),
    }];
    let actual = resolver.resolve("greet");

    assert_eq!(expected, actual);
}
