//! ADR 0010 & 0011: attribute-based (`generated_paths`) and
//! content-based (marker detection) generated-file skipping via
//! `analyze_diff`. Covers the deleted-wins-over-generated ordering, the
//! `include_generated` opt-out, and that an attribute-based skip
//! short-circuits before any content read.

use super::fake_reader;
use crate::diff::LineRange;
use crate::extract::{ExtractedSymbol, SymbolKind};
use crate::file_size::{FileSizeBand, FileSizeEntry};
use crate::pipeline::analyze_diff;
use crate::render::{FileReport, Report, ReportOrigin, SkipReason, SkippedFile};
use pretty_assertions::assert_eq;
use std::collections::{HashMap, HashSet};

#[test]
fn should_skip_path_as_generated_when_in_generated_paths_set() {
    let diff = "\
diff --git a/Cargo.lock b/Cargo.lock
index e69de29..4b825dc 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -1,1 +1,1 @@
-version = 1
+version = 2
";
    // No entry in the map: if the pipeline tried to read a
    // generated file, this would return an Err and fail the test.
    let read_file = fake_reader(HashMap::new());
    let generated_paths: HashSet<String> = ["Cargo.lock".to_string()].into_iter().collect();

    let report = analyze_diff(
        diff,
        read_file,
        None,
        None,
        true,
        &generated_paths,
        true,
        None,
    )
    .expect("analyze should succeed");

    let expected = vec![SkippedFile {
        path: "Cargo.lock".to_string(),
        reason: SkipReason::Generated,
    }];
    assert_eq!(expected, report.skipped);
}

// Regression test: a file that is both deleted and marked
// generated (e.g. a lockfile removed from a repo that also
// declares it `-diff`) must be reported as `Deleted`, not
// `Generated` — the fact that the file was removed is more
// important information for a reviewer than the (now moot)
// attribute it used to carry, and `Deleted` already carries no
// content to read either way.
#[test]
fn should_report_deleted_reason_when_a_deleted_path_is_also_marked_generated() {
    let diff = "\
diff --git a/Cargo.lock b/Cargo.lock
deleted file mode 100644
index 4b825dc..0000000
--- a/Cargo.lock
+++ /dev/null
@@ -1,1 +0,0 @@
-version = 1
";
    // No entry in the map: if the pipeline tried to read a deleted
    // file, this would return an Err and fail the test.
    let read_file = fake_reader(HashMap::new());
    let generated_paths: HashSet<String> = ["Cargo.lock".to_string()].into_iter().collect();

    let report = analyze_diff(
        diff,
        read_file,
        None,
        None,
        true,
        &generated_paths,
        true,
        None,
    )
    .expect("analyze should succeed");

    let expected = vec![SkippedFile {
        path: "Cargo.lock".to_string(),
        reason: SkipReason::Deleted,
    }];
    assert_eq!(expected, report.skipped);
}

#[test]
fn should_not_skip_path_when_generated_paths_set_is_empty() {
    let diff = "\
diff --git a/src/lib.rs b/src/lib.rs
index e69de29..4b825dc 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1,3 +1,3 @@
 fn foo(a: i32) -> i32 {
-    a
+    a + 1
 }
";
    let source = "\
fn foo(a: i32) -> i32 {
    a + 1
}
";
    let read_file = fake_reader(HashMap::from([("src/lib.rs", source)]));

    let report = analyze_diff(
        diff,
        read_file,
        None,
        None,
        true,
        &HashSet::new(),
        true,
        None,
    )
    .expect("analyze should succeed");

    let expected: Vec<SkippedFile> = Vec::new();
    assert_eq!(expected, report.skipped);
}

#[test]
fn should_skip_file_as_generated_when_content_has_code_generated_do_not_edit_marker() {
    let diff = "\
diff --git a/models/user.go b/models/user.go
index e69de29..4b825dc 100644
--- a/models/user.go
+++ b/models/user.go
@@ -1,1 +1,1 @@
-package models
+package models // updated
";
    let source = "\
// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.

package models
";
    let read_file = fake_reader(HashMap::from([("models/user.go", source)]));

    let report = analyze_diff(
        diff,
        read_file,
        None,
        None,
        true,
        &HashSet::new(),
        false,
        None,
    )
    .expect("analyze should succeed");

    let expected_files: Vec<FileReport> = Vec::new();
    let expected_skipped = vec![SkippedFile {
        path: "models/user.go".to_string(),
        reason: SkipReason::Generated,
    }];
    assert_eq!(expected_files, report.files);
    assert_eq!(expected_skipped, report.skipped);
}

#[test]
fn should_not_skip_file_as_generated_when_include_generated_is_true() {
    let diff = "\
diff --git a/models/user.go b/models/user.go
index e69de29..4b825dc 100644
--- a/models/user.go
+++ b/models/user.go
@@ -1,3 +1,3 @@
 // Code generated by SQLBoiler 4.19.5. DO NOT EDIT.

-func Foo() int { return 1 }
+func Foo() int { return 2 }
";
    let source = "\
// Code generated by SQLBoiler 4.19.5. DO NOT EDIT.

func Foo() int { return 2 }
";
    let read_file = fake_reader(HashMap::from([("models/user.go", source)]));

    let expected = Report {
        origin: ReportOrigin::Diff,
        files: vec![FileReport {
            path: "models/user.go".to_string(),
            symbols: vec![ExtractedSymbol {
                id: "models/user.go::Foo".to_string(),
                name: "Foo".to_string(),
                kind: SymbolKind::Function,
                signature: "func Foo() int".to_string(),
                range: LineRange { start: 3, end: 3 },
                container: None,
                referenced_names: vec!["int".to_string()],
                dependencies: vec![],
                omitted_dependency_matches: 0,
                is_test: false,
                classification: None,
                previous_signature: None,
            }],
        }],
        skipped: vec![],
        graph: crate::graph::SymbolGraph {
            nodes: vec![crate::graph::Node {
                id: "models/user.go::Foo".to_string(),
                path: "models/user.go".to_string(),
                name: "Foo".to_string(),
                is_test: false,
            }],
            edges: vec![],
            roots: vec!["models/user.go::Foo".to_string()],
        },
        tests: vec![],
        fan_ins: vec![],
        file_size_warnings: vec![],
        file_size_bands: vec![FileSizeEntry {
            path: "models/user.go".to_string(),
            line_count: 3,
            band: FileSizeBand::Normal,
        }],
        removed: vec![],
    };
    let actual = analyze_diff(
        diff,
        read_file,
        None,
        None,
        true,
        &HashSet::new(),
        true,
        None,
    )
    .expect("analyze should succeed");

    assert_eq!(expected, actual);
}

#[test]
fn should_not_skip_ordinary_file_with_no_generated_marker() {
    let diff = "\
diff --git a/src/lib.rs b/src/lib.rs
index e69de29..4b825dc 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1,3 +1,3 @@
 fn foo(a: i32) -> i32 {
-    a
+    a + 1
 }
";
    let source = "\
fn foo(a: i32) -> i32 {
    a + 1
}
";
    let read_file = fake_reader(HashMap::from([("src/lib.rs", source)]));

    let expected = Report {
        origin: ReportOrigin::Diff,
        files: vec![FileReport {
            path: "src/lib.rs".to_string(),
            symbols: vec![ExtractedSymbol {
                id: "src/lib.rs::foo".to_string(),
                name: "foo".to_string(),
                kind: SymbolKind::Function,
                signature: "fn foo(a: i32) -> i32".to_string(),
                range: LineRange { start: 1, end: 3 },
                container: None,
                referenced_names: vec![],
                dependencies: vec![],
                omitted_dependency_matches: 0,
                is_test: false,
                classification: None,
                previous_signature: None,
            }],
        }],
        skipped: vec![],
        graph: crate::graph::SymbolGraph {
            nodes: vec![crate::graph::Node {
                id: "src/lib.rs::foo".to_string(),
                path: "src/lib.rs".to_string(),
                name: "foo".to_string(),
                is_test: false,
            }],
            edges: vec![],
            roots: vec!["src/lib.rs::foo".to_string()],
        },
        tests: vec![],
        fan_ins: vec![],
        file_size_warnings: vec![],
        file_size_bands: vec![FileSizeEntry {
            path: "src/lib.rs".to_string(),
            line_count: 3,
            band: FileSizeBand::Normal,
        }],
        removed: vec![],
    };
    let actual = analyze_diff(
        diff,
        read_file,
        None,
        None,
        true,
        &HashSet::new(),
        false,
        None,
    )
    .expect("analyze should succeed");

    assert_eq!(expected, actual);
}

#[test]
fn should_skip_only_the_generated_file_when_diff_touches_both_kinds() {
    let diff = "\
diff --git a/models/user.go b/models/user.go
index e69de29..4b825dc 100644
--- a/models/user.go
+++ b/models/user.go
@@ -1,1 +1,1 @@
-// stale
+// Code generated by tool. DO NOT EDIT.
diff --git a/src/lib.rs b/src/lib.rs
index e69de29..4b825dc 100644
--- a/src/lib.rs
+++ b/src/lib.rs
@@ -1,3 +1,3 @@
 fn foo(a: i32) -> i32 {
-    a
+    a + 1
 }
";
    let generated_source = "// Code generated by tool. DO NOT EDIT.\n\npackage models\n";
    let normal_source = "fn foo(a: i32) -> i32 {\n    a + 1\n}\n";
    let read_file = fake_reader(HashMap::from([
        ("models/user.go", generated_source),
        ("src/lib.rs", normal_source),
    ]));

    let expected = Report {
        origin: ReportOrigin::Diff,
        files: vec![FileReport {
            path: "src/lib.rs".to_string(),
            symbols: vec![ExtractedSymbol {
                id: "src/lib.rs::foo".to_string(),
                name: "foo".to_string(),
                kind: SymbolKind::Function,
                signature: "fn foo(a: i32) -> i32".to_string(),
                range: LineRange { start: 1, end: 3 },
                container: None,
                referenced_names: vec![],
                dependencies: vec![],
                omitted_dependency_matches: 0,
                is_test: false,
                classification: None,
                previous_signature: None,
            }],
        }],
        skipped: vec![SkippedFile {
            path: "models/user.go".to_string(),
            reason: SkipReason::Generated,
        }],
        graph: crate::graph::SymbolGraph {
            nodes: vec![crate::graph::Node {
                id: "src/lib.rs::foo".to_string(),
                path: "src/lib.rs".to_string(),
                name: "foo".to_string(),
                is_test: false,
            }],
            edges: vec![],
            roots: vec!["src/lib.rs::foo".to_string()],
        },
        tests: vec![],
        fan_ins: vec![],
        file_size_warnings: vec![],
        file_size_bands: vec![FileSizeEntry {
            path: "src/lib.rs".to_string(),
            line_count: 3,
            band: FileSizeBand::Normal,
        }],
        removed: vec![],
    };
    let actual = analyze_diff(
        diff,
        read_file,
        None,
        None,
        true,
        &HashSet::new(),
        false,
        None,
    )
    .expect("analyze should succeed");

    assert_eq!(expected, actual);
}

// Regression test: an attribute-based generated_paths match must
// take priority and skip the file before its content is ever read
// — content-marker detection is purely additive coverage on top of
// ADR 0010's attribute-based skipping, not a second independent
// check that could disagree with it.
#[test]
fn should_not_read_file_content_when_already_skipped_by_generated_paths() {
    let diff = "\
diff --git a/Cargo.lock b/Cargo.lock
index e69de29..4b825dc 100644
--- a/Cargo.lock
+++ b/Cargo.lock
@@ -1,1 +1,1 @@
-version = 1
+version = 2
";
    // No entry in the map: if the pipeline tried to read this file
    // (to run the content-marker check), this would return an Err
    // and fail the test.
    let read_file = fake_reader(HashMap::new());
    let generated_paths: HashSet<String> = ["Cargo.lock".to_string()].into_iter().collect();

    let report = analyze_diff(
        diff,
        read_file,
        None,
        None,
        true,
        &generated_paths,
        false,
        None,
    )
    .expect("analyze should succeed");

    let expected = vec![SkippedFile {
        path: "Cargo.lock".to_string(),
        reason: SkipReason::Generated,
    }];
    assert_eq!(expected, report.skipped);
}
