//! ADR 0011: the `is_generated_content` marker-detection helper's
//! positive and negative cases (parametric via rstest, plus dedicated
//! regression cases for casing and the exact fifth-line boundary).

use crate::deps::is_generated_content;
use pretty_assertions::assert_eq;
use rstest::rstest;

#[rstest]
// Real-world SQLBoiler header (Go ORM code generator).
#[case::should_detect_sqlboiler_go_header(
    "// Code generated by SQLBoiler 4.19.5 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.\n\npackage models\n",
    true
)]
// protobuf-generated Go, no tool URL.
#[case::should_detect_protobuf_style_header(
    "// Code generated by protoc-gen-go. DO NOT EDIT.\n// versions:\n// \tprotoc-gen-go v1.28.0\n\npackage pb\n",
    true
)]
// Shell/Python-style `#` comment instead of Go's `//`.
#[case::should_detect_hash_comment_header(
    "#!/usr/bin/env python3\n# Code generated by codegen. DO NOT EDIT.\n\nimport sys\n",
    true
)]
// Facebook-style bare marker, no "Code generated" wording at all.
#[case::should_detect_at_generated_marker("// @generated\n\npackage models\n", true)]
#[case::should_return_false_when_marker_is_on_line_six_or_later(
    "line1\nline2\nline3\nline4\nline5\n// Code generated by tool. DO NOT EDIT.\n",
    false
)]
#[case::should_return_false_when_code_generated_present_without_do_not_edit(
    "// Code generated by tool.\n\npackage models\n",
    false
)]
#[case::should_return_false_when_content_has_no_marker_at_all(
    "fn foo() -> i32 {\n    1\n}\n",
    false
)]
fn is_generated_content_cases(#[case] content: &str, #[case] expected: bool) {
    let actual = is_generated_content(content);

    assert_eq!(expected, actual);
}

// Regression case pinning down the exact case sensitivity ADR 0011
// specifies (matches linguist's own casing): a differently-cased
// marker must not match.
#[test]
fn should_return_false_when_do_not_edit_casing_does_not_match() {
    let content = "// Code generated by tool. do not edit.\n";

    let actual = is_generated_content(content);

    assert!(!actual);
}

#[test]
fn should_return_true_when_marker_is_exactly_on_the_fifth_line() {
    let content = "line1\nline2\nline3\nline4\n// @generated\n";

    let actual = is_generated_content(content);

    assert!(actual);
}
